# Default values for sk-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:

  name: sk-backend

  labels: { "app": "backend" }

  replicaCount: 1

  image:
    repository: harbor/sk-backend
    tag: v1
    pullPolicy: IfNotPresent

  container:
    name: backend
    serverPort: 8080
    debugPort: 8000

  service:
    type: NodePort
    http:
      port: 8081
      targetPort: 8080
      nodePort: 30881
    debug:
      port: 9000
      targetPort: 8000
      nodePort: 30900

  persistence:
    logs:
      accessMode: ReadWriteOnce
      size: 100Mi
    licenses:
      accessMode: ReadWriteOnce
      size: 100Mi

  environment:
    spring:
      profiles:
        active: dev
    database:
      host: sk-postgres-service
      port: 5432
    scheduler:
      delay: 60000
      maxDays: 100
      maxMinutes: 10
    license:
      agentAddress: 127.0.0.1:8089
    notification:
      base:
        enabled: false
        delayMinutes: 15
        ipAddresses: 127.0.0.1:50052
        numbers:

  initContainer:
    image: postgres
    tag: 9.4-alpine

database:

  name: sk-postgres

  labels: { "app": "postgres" }

  replicaCount: 1

  image:
    repository: harbor/sk-database
    tag: v1
    pullPolicy: IfNotPresent

  container:
    name: postgres
    port: 5432

  headlessService:
    port: 5432

  externalService:
    type: NodePort
    port: 5432
    targetPort: 5432
    nodePort: 30432

  persistence:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi

imagePullSecrets: []
