{{- $database := .Values.database -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $database.name }}-service
  labels:
{{- include "database.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: {{ $database.headlessService.port }}
  selector:
{{- include "database.labels" . | indent 4 }}
